#!/bin/bash

# Set up the crontab to run run-record script every minute
chmod +x run-record
parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
sudo crontab -l -u $USER;
printf "MAILTO=\"\"\n* * * * * ${parent_path}/run-record" | sudo crontab -u $USER -
